name: Build Apk
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - run: flutter pub get
      # - run: flutter test
    - name: Create release.jks
      run: echo -n ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > android/release.jks
    - name: Create key.properties
      run: |
        echo 'storeFile=release.jks' > android/key.properties
        echo 'storePassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
        echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
        echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties
    - name: Build Apk
      run: flutter build apk
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: android
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Upload to Google Drive
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        upload-from: build/app/outputs/flutter-apk/app-release.apk
        upload-to: jknwr
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
